name: Build

on:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build package
        env:
          CI: "true"
        run: |
          npm install
          npm install -g vsce
          npm ci
          vsce package
